Add skip navigation link
WeAllCode/website pull request #851
Opened 2021-01-21 20:40 UTC by rgroves

This PR addresses accessibility concerns by adding a "skip to main content" link that will be visible to screen readers and via keyboard navigation. It also ensures that there is one main element around the main content of a page so that modern browsers & screen readers can detect the element that has the main ARIA landmark role within the page contents.

Please carefully review details of commit [9fc49a4](https://github.com/WeAllCode/website/commit/9fc49a4cb126b545ec8db2d8346a0f57f6cd1410) of this PR.

I ran through local testing and comparing pages to the live site for these changes. One notable difference is on the `programs` page, the 1px white bottom border that was on the Learn More/Volunteer button in the upcoming classes cards has been removed. I assumed (since this is the only button on the site that has this white border bottom) this was never really intended and happened as consequences of #812, but if that is a wanted design feature I can make adjustments to add it back in for those class buttons.

Closes #828

2021-01-25 18:32 UTC, karbassi requested changes
Overall, looks good. Thanks for the full explanation in 9fc49a4.

Can you move the `<main id="#main">` after the hero images?

2021-01-25 18:32 UTC, karbassi commented on weallcode/templates/weallcode/associate_board.html
> +  <main id="main">
The `#main` should be below the hero image. 

A good way to think about this is, where does the _main_ textual content start? The hero image is a visual accessory, not useful for non-sighted users.

2021-01-25 20:08 UTC, rgroves commented on weallcode/templates/weallcode/associate_board.html
> +  <main id="main">
Thanks for catching that. Latest commit reflects this change.

2021-01-26 01:51 UTC, karbassi approved these changes
LGTM

2021-01-26 01:52 UTC, merged